// Side-view room layouts. x in px, floor props sit on the floor (y = floor),
// wall props use an explicit y (top). `front:true` props draw over characters.
export const FLOOR = 150, CEIL = 62;

export const ROOMS = {
  cuarto: {
    name: 'Cuarto de Kazoo', w: 352,
    theme: { wall: '#6a5a8a', wall2: '#5a4a7a', pattern: 'stripes', floor: '#8c5a32', floorP: 'wood', ceil: '#2a2040' },
    props: [
      { t: 'door', x: 12, exit: 'city' }, { t: 'papel', x: 38, y: 96, red: true, id: 'aviso' },
      { t: 'bed', x: 56, messy: true, col: '#b8323c' },
      { t: 'window', x: 118, y: 80, w: 30, h: 24, curtain: '#e0a82e' },
      { t: 'table', x: 160, w: 30 }, { t: 'tv', x: 164, y: 136 },
      { t: 'poster', x: 206, y: 78, col: '#1a1a2a', col2: '#ff3cc8', text: 'VICE' },
      { t: 'calendar', x: 232, y: 84, mark: true },
      { t: 'stove', x: 262 }, { t: 'microwave', x: 264, y: 132 }, { t: 'fridge', x: 286 }, { t: 'sink', x: 308 },
    ],
    exits: [{ x: 12, w: 22, to: 'city', place: 'pension' }],
    music: null,
  },
  taqueria: {
    name: 'Tacos El Compa', w: 384,
    theme: { wall: '#f0c850', wall2: '#e8b840', pattern: 'tiles', floor: '#b04a3a', floorP: 'checker', ceil: '#6a3a1a' },
    props: [
      { t: 'door', x: 12, exit: 'city' },
      { t: 'cartel', x: 40, y: 72, w: 90, text: 'TACOS AL PASTOR $15', col: '#ffd23f', bg: '#8c1c28' },
      { t: 'table', x: 44, cloth: '#46b450' }, { t: 'chair', x: 34 }, { t: 'chair', x: 74, flip: true },
      { t: 'table', x: 104, cloth: '#d8323c' }, { t: 'chair', x: 94 }, { t: 'chair', x: 134, flip: true },
      { t: 'tv2', x: 150, y: 76 },
      { t: 'trompo', x: 236 }, { t: 'stove', x: 256, on: true }, { t: 'fridge', x: 330 },
      { t: 'counter', x: 196, w: 110, col: '#d8323c', tiles: true, front: true, cover: true },
      { t: 'plant', x: 360 },
      { t: 'cartel', x: 200, y: 74, w: 100, text: 'EL COMPA', col: '#f4f4f0', bg: '#1e6e3c' },
    ],
    exits: [{ x: 12, w: 22, to: 'city', place: 'taqueria' }],
  },
  tiendita: {
    name: 'Abarrotes Lupita', w: 320,
    theme: { wall: '#28b4a0', wall2: '#20a090', pattern: 'plain', floor: '#c8c8c0', floorP: 'checker', ceil: '#1a5a50' },
    props: [
      { t: 'door', x: 12, exit: 'city' },
      { t: 'shelf', x: 50, w: 40, h: 44 }, { t: 'shelf', x: 100, w: 40, h: 44 },
      { t: 'fridge', x: 150 }, { t: 'fridge', x: 168 },
      { t: 'register', x: 236 }, { t: 'counter', x: 214, w: 60, col: '#f4f4f0', front: true, cover: true },
      { t: 'cartel', x: 200, y: 72, w: 90, text: 'ABARROTES LUPITA', col: '#f4f4f0', bg: '#d8323c' },
      { t: 'shelf', x: 280, w: 30, h: 30 },
    ],
    exits: [{ x: 12, w: 22, to: 'city', place: 'tiendita' }],
  },
  donchuy: {
    name: 'Casa de Don Chuy', w: 416,
    theme: { wall: '#e8a0c0', wall2: '#d890b0', pattern: 'damask', floor: '#e8e0d0', floorP: 'marble', ceil: '#6a3a50' },
    props: [
      { t: 'door', x: 12, exit: 'city', col: '#8c5a32' },
      { t: 'plant', x: 44 }, { t: 'cuadro', x: 70, y: 84 }, { t: 'sofa', x: 90, col: '#d8323c' },
      { t: 'pool', x: 160 }, { t: 'lamp', x: 216, col: '#ffd23f' },
      { t: 'window', x: 240, y: 78, w: 36, h: 26, curtain: '#8c1c28' },
      { t: 'desk', x: 300, w: 40, papers: true, cover: true }, { t: 'chair', x: 330 }, { t: 'trophy', x: 306, y: 134 },
      { t: 'safe', x: 370 }, { t: 'plant', x: 396 },
    ],
    exits: [{ x: 12, w: 22, to: 'city', place: 'donchuy' }],
  },
  bar: {
    name: 'La Última Risa', w: 544,
    theme: { wall: '#3a1a4a', wall2: '#2a1038', pattern: 'bricks', floor: '#2a1a1a', floorP: 'wood', ceil: '#140a1a', dim: 0.25 },
    props: [
      { t: 'door', x: 12, exit: 'city', col: '#5a1a3a' },
      { t: 'arcade', x: 50, id: 'arcade' }, { t: 'arcade', x: 70 },
      { t: 'jukebox', x: 100 },
      { t: 'sign', x: 150, y: 72, text: 'LA ÚLTIMA RISA', neon: true, col: '#ff3cc8' },
      { t: 'tv2', x: 250, y: 74 },
      { t: 'bottles', x: 280, y: 94, w: 70 },
      { t: 'bar', x: 270, w: 110, front: true, cover: true },
      { t: 'stool', x: 280, front: true }, { t: 'stool', x: 304, front: true }, { t: 'stool', x: 328, front: true }, { t: 'stool', x: 352, front: true },
      { t: 'pool', x: 410 }, { t: 'table', x: 470, cover: true }, { t: 'chair', x: 460 }, { t: 'chair', x: 500, flip: true },
      { t: 'poster', x: 430, y: 80, col: '#ffd23f', col2: '#d8323c', text: 'XXX' },
    ],
    exits: [{ x: 12, w: 22, to: 'city', place: 'bar' }],
  },
  disfraces: {
    name: 'Disfraces Carnaval', w: 352,
    theme: { wall: '#f08c28', wall2: '#e07c18', pattern: 'diamonds', floor: '#6a3a8a', floorP: 'checker', ceil: '#5a2a18' },
    props: [
      { t: 'door', x: 12, exit: 'city' },
      { t: 'rack', x: 50 }, { t: 'rack', x: 90 },
      { t: 'masks', x: 140, y: 78, id: 'masks' }, { t: 'mirror', x: 196, y: 90 },
      { t: 'rack', x: 230 },
      { t: 'counter', x: 270, w: 60, col: '#8c46c8', front: true, cover: true }, { t: 'register', x: 290 },
    ],
    exits: [{ x: 12, w: 22, to: 'city', place: 'disfraces' }],
  },
  comandancia: {
    name: 'Comandancia', w: 480,
    theme: { wall: '#a8b0c0', wall2: '#98a0b0', pattern: 'panels', floor: '#5a5a64', floorP: 'tiles', ceil: '#2a2a3a' },
    props: [
      { t: 'door', x: 12, exit: 'city', col: '#3a4a6a' },
      { t: 'bench', x: 40, back: true }, { t: 'flag', x: 90 },
      { t: 'wanted', x: 110, y: 84 }, { t: 'wanted', x: 128, y: 84 }, { t: 'wanted', x: 146, y: 84 },
      { t: 'desk', x: 180, papers: true, cover: true }, { t: 'computer', x: 190, y: 134 }, { t: 'chair', x: 212 },
      { t: 'desk', x: 260, papers: true, cover: true }, { t: 'computer', x: 270, y: 134 }, { t: 'fan', x: 250, y: 62 },
      { t: 'window', x: 310, y: 78, w: 34, h: 22 },
      { t: 'cell', x: 380 }, { t: 'cell', x: 430 },
    ],
    exits: [{ x: 12, w: 22, to: 'city', place: 'comandancia' }],
  },
  escondite: {
    name: 'Taller abandonado', w: 480,
    theme: { wall: '#5a5a5e', wall2: '#4a4a4e', pattern: 'concrete', floor: '#3a3a3e', floorP: 'concrete', ceil: '#1a1a1e', dim: 0.15 },
    props: [
      { t: 'door', x: 12, exit: 'city', col: '#5a4a3a' },
      { t: 'toolwall', x: 40, y: 88 }, { t: 'workbench', x: 42 },
      { t: 'barrel', x: 92, col: '#d8323c' }, { t: 'barrel', x: 106, col: '#3c64dc' },
      { t: 'lamp', x: 140, col: '#fff08c' },
      { t: 'whiteboard', x: 160, y: 72, plan: false, id: 'plan' },
      { t: 'sofa', x: 240, col: '#6a5a3a', stain: true, cover: true }, { t: 'cooler', x: 284 }, { t: 'radio', x: 300, y: 136 },
      { t: 'crates', x: 330, cover: true },
      { t: 'fan', x: 380, y: 62 },
      { t: 'window', x: 400, y: 80, w: 30, h: 18 },
      { t: 'crate', x: 440, cover: true },
    ],
    exits: [{ x: 12, w: 22, to: 'city', place: 'escondite' }],
  },
  galpon: {
    name: 'Galpón de La Tía Gris', w: 640,
    theme: { wall: '#6a6a4a', wall2: '#5a5a3e', pattern: 'corrugated', floor: '#4a4a3a', floorP: 'concrete', ceil: '#1e1e14', dim: 0.1 },
    props: [
      { t: 'door', x: 12, exit: 'city', col: '#4a5a3a' },
      { t: 'crates', x: 44, cover: true }, { t: 'gunrack', x: 90, y: 86 }, { t: 'table', x: 130, w: 34, cover: true },
      { t: 'lamp', x: 176 }, { t: 'desk', x: 196, cover: true }, { t: 'radio', x: 206, y: 134 },
      { t: 'cartel', x: 250, y: 70, w: 80, text: 'NO DUDES', col: '#d8323c', bg: '#1a1a14' },
      { t: 'rope', x: 300 },
      { t: 'target', x: 420 }, { t: 'target', x: 480 }, { t: 'target', x: 540 },
      { t: 'crate', x: 600, s: 22 },
    ],
    exits: [{ x: 12, w: 22, to: 'city', place: 'galpon' }],
  },
  bodega: {
    name: 'Bodega 7', w: 960, dark: true,
    theme: { wall: '#4a4a52', wall2: '#3e3e46', pattern: 'corrugated', floor: '#2e2e34', floorP: 'concrete', ceil: '#101014' },
    props: [
      { t: 'door', x: 12, exit: 'city', col: '#4a4a52' },
      { t: 'boxes', x: 60, cover: true }, { t: 'crates', x: 130, cover: true }, { t: 'locker', x: 180, hide: true },
      { t: 'forklift', x: 230 }, { t: 'boxes', x: 300, cover: true }, { t: 'barrel', x: 350 }, { t: 'barrel', x: 364, col: '#46b450' },
      { t: 'locker', x: 420, hide: true }, { t: 'crates', x: 470, cover: true }, { t: 'boxes', x: 540, cover: true },
      { t: 'lamp', x: 600, light: true }, { t: 'crate', x: 640, cover: true }, { t: 'locker', x: 700, hide: true },
      { t: 'boxes', x: 760, cover: true }, { t: 'window', x: 820, y: 76, w: 26, h: 16 },
      { t: 'workbench', x: 860 }, { t: 'drill', x: 868, y: 132, id: 'drill' }, { t: 'lamp', x: 920, light: true },
    ],
    exits: [{ x: 12, w: 22, to: 'city', place: 'bodega' }],
  },
  tuercas: {
    name: 'Taller El Tuercas', w: 704,
    theme: { wall: '#7a6a5a', wall2: '#6a5a4a', pattern: 'bricks', floor: '#4a4038', floorP: 'concrete', ceil: '#2a2018' },
    props: [
      { t: 'door', x: 12, exit: 'city', label: 'FRENTE' },
      { t: 'carside', x: 60, col: '#8c46c8', hoodOpen: true, cover: true }, { t: 'toolwall', x: 140, y: 86 }, { t: 'workbench', x: 142 },
      { t: 'tank', x: 196 }, { t: 'barrel', x: 216 },
      { t: 'poster', x: 250, y: 80, col: '#f4f4f0', col2: '#d8323c', text: 'MOTUL' },
      { t: 'crates', x: 280, cover: true }, { t: 'carside', x: 330, col: '#46b450', cover: true },
      { t: 'door', x: 410, col: '#5a4a3a', label: 'OFICINA', id: 'oficinaDoor' },
      { t: 'desk', x: 450, papers: true, cover: true }, { t: 'chair', x: 486 }, { t: 'calendar', x: 470, y: 86 }, { t: 'safe', x: 520, id: 'safe' },
      { t: 'locker', x: 560, hide: true }, { t: 'plant', x: 590 }, { t: 'boxes', x: 620, cover: true },
      { t: 'door', x: 676, label: 'ATRÁS', col: '#5a4a3a' },
    ],
    exits: [{ x: 12, w: 22, to: 'city', place: 'tuercas' }, { x: 676, w: 22, to: 'city', place: 'tuercas' }],
  },
  banco: {
    name: 'Banco Federal', w: 896,
    theme: { wall: '#e8e4dc', wall2: '#d8d4cc', pattern: 'marble', floor: '#c8c8d0', floorP: 'marble', ceil: '#8a8070' },
    props: [
      { t: 'door', x: 12, exit: 'city', col: '#6a8cac' },
      { t: 'plant', x: 44 }, { t: 'flag', x: 64 }, { t: 'atm', x: 84 },
      { t: 'window', x: 110, y: 74, w: 40, h: 30 },
      { t: 'camera', x: 160, y: 64, face: 1, id: 'cam1' },
      { t: 'rope', x: 180 }, { t: 'rope', x: 216 }, { t: 'bench', x: 260, back: true, cover: true },
      { t: 'camera', x: 300, y: 64, face: -1, id: 'cam2' },
      { t: 'cartel', x: 330, y: 70, w: 110, text: 'BANCO FEDERAL', col: '#c8a040', bg: '#1e2c50' },
      { t: 'plant', x: 460 }, { t: 'camera', x: 480, y: 64, face: 1, id: 'cam3' },
      { t: 'teller', x: 520, w: 150, cover: true, front: true },
      { t: 'alarm', x: 640, y: 116, id: 'alarm' },
      { t: 'camera', x: 690, y: 64, face: -1, id: 'cam4', crooked: true },
      { t: 'door', x: 720, col: '#5a4a3a', label: 'GERENCIA', id: 'gerencia' },
      { t: 'window', x: 760, y: 74, w: 30, h: 30 },
      { t: 'camera', x: 800, y: 64, face: -1, id: 'cam5' },
      { t: 'door', x: 840, col: '#5a5a64', label: 'BÓVEDA', id: 'bovedaDoor' },
      { t: 'camera', x: 874, y: 64, face: -1, id: 'cam6' },
    ],
    exits: [{ x: 12, w: 22, to: 'city', place: 'banco' }],
  },
  gerencia: {
    name: 'Gerencia', w: 320,
    theme: { wall: '#c8b8a0', wall2: '#b8a890', pattern: 'panels', floor: '#6e4424', floorP: 'wood', ceil: '#4a3a2a' },
    props: [
      { t: 'door', x: 12, col: '#5a4a3a' }, { t: 'plant', x: 50 }, { t: 'cuadro', x: 90, y: 84 },
      { t: 'desk', x: 140, w: 40, papers: true, cover: true }, { t: 'computer', x: 152, y: 134 }, { t: 'chair', x: 184 },
      { t: 'window', x: 220, y: 76, w: 36, h: 26 }, { t: 'safe', x: 280 },
    ],
    exits: [{ x: 12, w: 22, to: 'banco', spawnX: 730 }],
  },
  boveda: {
    name: 'Sótano — Bóveda', w: 704,
    theme: { wall: '#6a6a74', wall2: '#5a5a64', pattern: 'panels', floor: '#3a3a44', floorP: 'tiles', ceil: '#1a1a24' },
    props: [
      { t: 'door', x: 12, col: '#5a5a64', label: 'ARRIBA' },
      { t: 'camera', x: 120, y: 64, face: 1, id: 'bcam1' }, { t: 'lockers', x: 0 },
      { t: 'locker', x: 160, hide: true }, { t: 'locker', x: 176, hide: true },
      { t: 'camera', x: 280, y: 64, face: -1, id: 'bcam2' },
      { t: 'boxes', x: 320, cover: true },
      { t: 'camera', x: 420, y: 64, face: 1, id: 'bcam3' },
      { t: 'locker', x: 460, hide: true },
      { t: 'cartel', x: 500, y: 70, w: 80, text: 'ÁREA RESTRINGIDA', col: '#ffd23f', bg: '#8c1c28' },
      { t: 'vault', x: 610, id: 'vault' },
    ],
    exits: [{ x: 12, w: 22, to: 'banco', spawnX: 850 }],
  },
  joyeria: {
    name: 'Joyería Brillante — hace 3 años', w: 576, dark: true,
    theme: { wall: '#3a2a4a', wall2: '#2e2040', pattern: 'damask', floor: '#2a2a34', floorP: 'marble', ceil: '#140a1a' },
    props: [
      { t: 'window', x: 30, y: 76, w: 40, h: 30 },
      { t: 'showcase', x: 90, id: 'sc1' }, { t: 'showcase', x: 150, id: 'sc2' }, { t: 'showcase', x: 210, id: 'sc3' },
      { t: 'lamp', x: 262, light: true },
      { t: 'showcase', x: 290, id: 'sc4' }, { t: 'showcase', x: 350, id: 'sc5' },
      { t: 'safe', x: 420, id: 'jsafe' }, { t: 'boxes', x: 460, cover: true },
      { t: 'door', x: 530, label: 'PUERTA TRASERA', id: 'back' },
    ],
    exits: [],
  },
  azotea: {
    name: 'Azotea de la pensión', w: 400, outdoor: true, night: true,
    theme: { floor: '#6a6a70', floorP: 'roof', sky: 'night' },
    props: [
      { t: 'moon', x: 300, y: 12 },
      { t: 'skyline', x: -40, y: 138, w: 480, neon: true },
      { t: 'antenna', x: 40 }, { t: 'tank', x: 70 }, { t: 'clothes', x: 110 },
      { t: 'ac', x: 330 }, { t: 'ac', x: 352 }, { t: 'cooler', x: 250 },
      { t: 'door', x: 12, label: 'ESCALERA' },
    ],
    exits: [{ x: 12, w: 22, to: 'city', place: 'pension' }],
  },
  campo: {
    name: 'El campo', w: 640, outdoor: true, night: true,
    theme: { floor: '#3a2a18', floorP: 'dirt', sky: 'night', ground: '#1e3a1a' },
    props: [
      { t: 'moon', x: 420, y: 16 },
      { t: 'fence', x: 20, w: 80 }, { t: 'bush', x: 140 },
      { t: 'bigtree', x: 330, id: 'arbol' },
      { t: 'bush', x: 520 }, { t: 'fence', x: 560, w: 70 },
      { t: 'grassfg', x: 0, y: 152, w: 640, front: true },
    ],
    exits: [{ x: 10, w: 20, to: 'city', place: 'campo' }],
  },
  camino: {
    name: 'El camino', w: 480, outdoor: true,
    theme: { floor: '#8a6a44', floorP: 'dirt', sky: 'dusk', ground: '#6a7a2a' },
    props: [
      { t: 'fence', x: 10, w: 120 }, { t: 'tree', x: 380, col: '#2a4a1e' }, { t: 'bush', x: 200 }, { t: 'bush', x: 260 },
      { t: 'lightpole', x: 150 },
      { t: 'grassfg', x: 0, y: 152, w: 480, front: true },
    ],
    exits: [],
  },
  clinica: {
    name: 'Clínica', w: 320,
    theme: { wall: '#e8f0f0', wall2: '#d8e8e8', pattern: 'tiles', floor: '#c8d8d8', floorP: 'tiles', ceil: '#6a8a8a' },
    props: [
      { t: 'door', x: 12, exit: 'city' }, { t: 'bench', x: 50, back: true }, { t: 'plant', x: 100 },
      { t: 'bed', x: 150, col: '#5adcf0' }, { t: 'window', x: 220, y: 78 }, { t: 'desk', x: 262 },
    ],
    exits: [{ x: 12, w: 22, to: 'city', place: 'clinica' }],
  },
};

// ---------------------------------------------------------------- shops (one room per business)
import { SHOPS } from '../data/shops.js';
const SHOP_ROOMS = {
  ropa: (sh) => ({
    theme: { wall: sh.fancy ? '#2a1a3a' : '#f8d0e0', wall2: sh.fancy ? '#3a2450' : '#f0bcd0', pattern: sh.fancy ? 'damask' : 'stripes', floor: sh.fancy ? '#e8e0d0' : '#c8b8a8', floorP: sh.fancy ? 'marble' : 'wood', ceil: '#5a2a40' },
    props: [
      { t: 'door', x: 12, exit: 'city' },
      { t: 'rack', x: 48 }, { t: 'rack', x: 84 }, { t: 'mirror', x: 128, y: 90 },
      { t: 'clothes', x: 158, y: 84 }, { t: 'rack', x: 190 },
      { t: 'cartel', x: 214, y: 72, w: 90, text: sh.sign, col: '#f4f4f0', bg: sh.roof },
      { t: 'counter', x: 232, w: 60, col: sh.roof, front: true, cover: true }, { t: 'register', x: 252 },
      { t: 'plant', x: 300 },
    ],
  }),
  zapateria: (sh) => ({
    theme: { wall: '#e8e8f0', wall2: '#d8d8e4', pattern: 'panels', floor: '#3a3a44', floorP: 'tiles', ceil: '#1e1e2a' },
    props: [
      { t: 'door', x: 12, exit: 'city' },
      { t: 'shelf', x: 44, w: 44, h: 50 }, { t: 'shelf', x: 96, w: 44, h: 50 },
      { t: 'bench', x: 150 }, { t: 'mirror', x: 188, y: 96 },
      { t: 'cartel', x: 210, y: 72, w: 90, text: sh.sign, col: '#101018', bg: sh.awning === '#101018' ? '#46b450' : '#ffd23f' },
      { t: 'counter', x: 232, w: 60, col: sh.roof, front: true, cover: true }, { t: 'register', x: 252 },
    ],
  }),
  restaurante: (sh) => ({
    theme: { wall: sh.menu === 'sushi' ? '#f0ece0' : sh.menu === 'mariscos' ? '#5adcf0' : '#ffd890', wall2: sh.menu === 'sushi' ? '#d8323c' : sh.menu === 'mariscos' ? '#3cb4d0' : '#f0c060', pattern: sh.menu === 'sushi' ? 'panels' : 'tiles', floor: '#8c5a32', floorP: sh.menu === 'sushi' ? 'wood' : 'checker', ceil: '#3a2a1a' },
    props: [
      { t: 'door', x: 12, exit: 'city' },
      { t: 'table', x: 44, cloth: '#f4f4f0' }, { t: 'chair', x: 34 }, { t: 'chair', x: 74, flip: true },
      { t: 'table', x: 104, cloth: sh.roof }, { t: 'chair', x: 94 }, { t: 'chair', x: 134, flip: true },
      { t: 'cartel', x: 150, y: 72, w: 70, text: 'MENÚ', col: '#f4f4f0', bg: '#1a1a2a' },
      { t: 'stove', x: 250, on: true }, { t: 'fridge', x: 290 },
      { t: 'counter', x: 200, w: 100, col: sh.roof, tiles: true, front: true, cover: true },
      { t: 'cartel', x: 196, y: 90, w: 100, text: sh.sign, col: '#f4f4f0', bg: sh.roof },
    ],
  }),
  bar: (sh) => ({
    theme: { wall: '#3a2418', wall2: '#2a180e', pattern: 'bricks', floor: '#2a1a12', floorP: 'wood', ceil: '#140a06', dim: 0.2 },
    props: [
      { t: 'door', x: 12, exit: 'city', col: '#5a3a1a' },
      { t: 'jukebox', x: 44 }, { t: 'pool', x: 80 },
      { t: 'sign', x: 150, y: 72, text: sh.sign, neon: true, col: sh.awning },
      { t: 'bottles', x: 196, y: 94, w: 90 },
      { t: 'bar', x: 186, w: 120, front: true, cover: true },
      { t: 'stool', x: 196, front: true }, { t: 'stool', x: 222, front: true }, { t: 'stool', x: 248, front: true },
    ],
  }),
};
for (const sh of SHOPS) {
  ROOMS[sh.id] = { name: sh.name, w: 320, ...SHOP_ROOMS[sh.kind](sh), exits: [{ x: 12, w: 22, to: 'city', place: sh.id }], shop: sh.id };
}
